"""
/***************************************************************************
 StreckenkmFinder
                                 A QGIS plugin
 Klicke auf eine Karte und erhalte den nähsten Streckenkm
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-15
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Christoph Mellüh
        email                : christoph.mellueh@deutschebahn.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path
from .db_streckenkm.point_finder import NearestPointFinder
from PyQt5.QtWidgets import QMessageBox
from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator,Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsProject,QgsVectorLayer
from qgis.gui import QgisInterface,QgsHighlight

from PyQt5.QtCore import Qt

from .db_streckenkm.dock_widget import DockWidget
from .db_streckenkm.map_tool import MapTool,LAYER_NAME
from . import get_icon_path

class StreckenkmFinder:
    """QGIS Plugin Implementation."""

    def __init__(self, iface:QgisInterface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'StreckenkmFinder_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&DB_Streckenkm')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        self.canvas = iface.mapCanvas()
        self.iface.mapCanvas().mapToolSet.connect(self.map_tool_changed)

        # Declare DockWidget Widget
        self.dockwidget:DockWidget = None
        # Declare MapTool
        self.map_tool: MapTool | None = None
        self.active_highlights:list[QgsHighlight] = list()
        QCoreApplication.instance().aboutToQuit.connect(self.destroy_hidden_layer)

    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('StreckenkmFinder', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = get_icon_path()

        # Add Toolbar Action
        self.add_action(
            icon_path,
            text=self.tr(u'Streckenkilometer'),
            callback=self.run,
            parent=self.iface.mainWindow(),
            add_to_toolbar=True)

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        if self.map_tool is not None:
            self.map_tool.deleteLater()
            if self.canvas.mapTool() == self.map_tool:
                self.canvas.setMapTool(None, clean=True)

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&DB_Streckenkm'),
                action)
            self.iface.removeToolBarIcon(action)
        if self.dockwidget:
            self.iface.removeDockWidget(self.dockwidget)
        layers = QgsProject.instance().mapLayers()
        for layer_id, layer in layers.items():
            if layer.name() == LAYER_NAME:
                QgsProject.instance().removeMapLayer(layer_id)
        self.remove_highlights()
        self.canvas.repaint()
    def destroy_hidden_layer(self):
        self.remove_highlights()
        self.map_tool.delete_lines()

    def map_tool_changed(self,new_tool,old_tool):
        if isinstance(old_tool, MapTool):
            self.destroy_hidden_layer()

    def activate_maptool(self):
        self.dockwidget.tab_widget.setTabEnabled(self.dockwidget.data_widget_index, True)
        self.dockwidget.tab_widget.setTabEnabled(self.dockwidget.layer_transformer_index, True)

        self.dockwidget.tab_widget.setCurrentIndex(self.dockwidget.data_widget_index)
        self.map_tool = MapTool(self.iface, self.dockwidget.settings_widget)
        self.map_tool.data_widget = self.dockwidget.data_widget
        self.dockwidget.maptool = self.map_tool

        self.map_tool.point_found.connect(self.dockwidget.point_found)
        self.map_tool.highlight_created.connect(self.map_tool_created_highlight)
        self.map_tool.request_highlight_deleted.connect(self.remove_highlights)
        self.iface.mapCanvas().setMapTool(self.map_tool)

    def map_tool_created_highlight(self,highlight:QgsHighlight):
        self.active_highlights.append(highlight)

    def remove_highlights(self):
        for highlight in self.active_highlights:
            highlight.hide()
            del highlight
        self.active_highlights = list()


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        from .db_streckenkm.dock_widget import DockWidget
        if not self.dockwidget:
            self.dockwidget = DockWidget(self.iface.mainWindow(),self.iface)
            self.iface.addDockWidget(Qt.DockWidgetArea.AllDockWidgetAreas, self.dockwidget)
            self.dockwidget.settings_widget.spatial_index_created.connect(self.activate_maptool)
            return
        if not self.dockwidget.isVisible():
            self.dockwidget.activate()
            return

        if not self.dockwidget.hasFocus():
            self.dockwidget.activate()

        if not self.dockwidget.is_maptool_available():
            QMessageBox.warning(None,self.tr("Warning"), self.tr("You need to create a Spatial Index first"))
            return

        self.activate_maptool()
