# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\DataWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 583)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.value_layout = QtWidgets.QGridLayout()
        self.value_layout.setHorizontalSpacing(6)
        self.value_layout.setObjectName("value_layout")
        self.gridLayout_2.addLayout(self.value_layout, 3, 0, 1, 3)
        self.label_ortho_val = QtWidgets.QLabel(Form)
        self.label_ortho_val.setObjectName("label_ortho_val")
        self.gridLayout_2.addWidget(self.label_ortho_val, 1, 1, 1, 1)
        self.label_km = QtWidgets.QLabel(Form)
        self.label_km.setObjectName("label_km")
        self.gridLayout_2.addWidget(self.label_km, 0, 0, 1, 1)
        self.label_km_val = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_km_val.sizePolicy().hasHeightForWidth())
        self.label_km_val.setSizePolicy(sizePolicy)
        self.label_km_val.setObjectName("label_km_val")
        self.gridLayout_2.addWidget(self.label_km_val, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 3)
        self.pushButton_ortho = QtWidgets.QPushButton(Form)
        self.pushButton_ortho.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_ortho.setObjectName("pushButton_ortho")
        self.gridLayout_2.addWidget(self.pushButton_ortho, 1, 2, 1, 1)
        self.pushButton_km = QtWidgets.QPushButton(Form)
        self.pushButton_km.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_km.setObjectName("pushButton_km")
        self.gridLayout_2.addWidget(self.pushButton_km, 0, 2, 1, 1)
        self.label_ortho = QtWidgets.QLabel(Form)
        self.label_ortho.setObjectName("label_ortho")
        self.gridLayout_2.addWidget(self.label_ortho, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_ortho_val.setText(_translate("Form", "Value Ortho"))
        self.label_km.setText(_translate("Form", "Kilometer"))
        self.label_km_val.setText(_translate("Form", "Value Kilomater"))
        self.pushButton_ortho.setText(_translate("Form", " "))
        self.pushButton_km.setText(_translate("Form", " "))
        self.label_ortho.setText(_translate("Form", "Orthogonal Distance"))
