# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 42)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.pushbutton_copy = QtWidgets.QPushButton(Form)
        self.pushbutton_copy.setMaximumSize(QtCore.QSize(24, 24))
        self.pushbutton_copy.setObjectName("pushbutton_copy")
        self.gridLayout.addWidget(self.pushbutton_copy, 0, 2, 1, 1)
        self.label_value = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_value.sizePolicy().hasHeightForWidth())
        self.label_value.setSizePolicy(sizePolicy)
        self.label_value.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.label_value.setObjectName("label_value")
        self.gridLayout.addWidget(self.label_value, 0, 1, 1, 1)
        self.label_text = QtWidgets.QLabel(Form)
        self.label_text.setObjectName("label_text")
        self.gridLayout.addWidget(self.label_text, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushbutton_copy.setText(_translate("Form", "C"))
        self.label_value.setText(_translate("Form", "Value"))
        self.label_text.setText(_translate("Form", "Kilometer"))
