# -*- coding: utf-8 -*-
"""
/***************************************************************************
 StreckenkmFinderDialog
                                 A QGIS plugin
 Klicke auf eine Karte und erhalte den nähsten Streckenkm
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-15
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Christoph Mellüh
        email                : christoph.mellueh@deutschebahn.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt import QtCore, QtWidgets
from qgis.PyQt.QtGui import QIcon
from qgis.core import Qgis, QgsSpatialIndex, QgsVectorLayer
from qgis.gui import QgsFieldComboBox, QgsMapLayerComboBox

from .. import get_icon_path
from ..ui.ui_SettingsWidget import Ui_SettingsWidget


class SettingsWidget(QtWidgets.QWidget, Ui_SettingsWidget):
    spatial_index_created = QtCore.pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(SettingsWidget, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.listWidget.itemChanged.connect(self.item_changed)
        self.comboBox_layer: QgsMapLayerComboBox
        self.comboBox_field: QgsFieldComboBox

        self.comboBox_layer.setShowCrs(True)
        self.comboBox_layer.setFilters(Qgis.LayerFilter.VectorLayer)

        self.comboBox_layer.layerChanged.connect(self.layer_changed)
        self.setWindowIcon(QIcon(get_icon_path()))
        self.spatial_index_dict: dict[QgsVectorLayer, QgsSpatialIndex] = dict()
        self.settings_dict: dict[QgsVectorLayer, list] = dict()

        self.pushButton.clicked.connect(self.create_spatial_index)
        self.checkBox_select_all.clicked.connect(self.select_all_clicked)
        self.layer_changed()

    def select_all_clicked(self):
        cs = self.checkBox_select_all.checkState()
        for i in range(self.listWidget.count()):
            self.listWidget.item(i).setCheckState(cs)

    @property
    def layer(self) -> QgsVectorLayer | None:
        return self.comboBox_layer.currentLayer()

    @property
    def start_field(self):
        return self.comboBox_field.currentField()

    def create_spatial_index(self):
        # Build spatial index for the point layer
        self.spatial_index_dict[self.layer] = QgsSpatialIndex(self.layer.getFeatures())
        self.spatial_index_created.emit()

    def item_changed(self, focus_item: QtWidgets.QListWidgetItem):
        new_checkstate = focus_item.checkState()
        items = self.listWidget.selectedItems()
        for item in items:
            item.setCheckState(new_checkstate)
        self.save_settings()
        if self.all_items_are_checked():
            self.checkBox_select_all.setChecked(True)
        else:
            self.checkBox_select_all.setChecked(False)

    def all_items_are_checked(self):
        items = [self.listWidget.item(i) for i in range(self.listWidget.count())]
        checkstates = set(item.checkState() for item in items)
        return checkstates == {QtCore.Qt.CheckState.Checked}

    def get_settings(self):
        field_name = self.start_field
        attribute_is_real = self.checkBox_is_float.isChecked()
        ignore_sidings = self.checkBox_ignore_empty.isChecked()
        checked_fields = self.get_checked_field_names()
        return self.layer, field_name, attribute_is_real, ignore_sidings, checked_fields

    def get_checked_field_names(self):
        checked_fields = list()
        for row in range(self.listWidget.count()):
            item = self.listWidget.item(row)
            if item.checkState() == QtCore.Qt.Checked:
                checked_fields.append(item.text())
        return checked_fields

    def layer_changed(self):
        layer = self.layer
        self.comboBox_field.setLayer(layer)
        if not isinstance(layer, QgsVectorLayer):
            return
        if self.settings_dict.get(layer) is None:
            field_name, attribute_is_real, ignore_sidings, checked_fields = None, None, None, None
        else:
            field_name, attribute_is_real, ignore_sidings, checked_fields = self.settings_dict[layer]

        field_names = [field.name() for field in layer.fields()]
        self.checkBox_is_float.setChecked(True if attribute_is_real else False)
        self.checkBox_ignore_empty.setChecked(True if ignore_sidings else False)

        self.listWidget.clear()
        self.checkBox_select_all.setChecked(False)
        if not checked_fields:
            checked_fields = []
        for name in field_names:
            item = QtWidgets.QListWidgetItem(name)
            item.setFlags(item.flags() | QtCore.Qt.ItemIsEditable)
            if name in checked_fields:
                item.setCheckState(QtCore.Qt.Checked)
            else:
                item.setCheckState(QtCore.Qt.Unchecked)
            self.listWidget.addItem(item)

    def save_settings(self):
        layer, field_name, attribute_is_real, ignore_sidings, checked_fields = self.get_settings()
        self.settings_dict[layer] = [field_name, attribute_is_real, ignore_sidings, checked_fields]
