# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\DataWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataWidget(object):
    def setupUi(self, DataWidget):
        DataWidget.setObjectName("DataWidget")
        DataWidget.resize(657, 616)
        self.gridLayout_2 = QtWidgets.QGridLayout(DataWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_km_val = QtWidgets.QLabel(DataWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_km_val.sizePolicy().hasHeightForWidth())
        self.label_km_val.setSizePolicy(sizePolicy)
        self.label_km_val.setObjectName("label_km_val")
        self.gridLayout_2.addWidget(self.label_km_val, 0, 1, 1, 1)
        self.label_ortho = QtWidgets.QLabel(DataWidget)
        self.label_ortho.setObjectName("label_ortho")
        self.gridLayout_2.addWidget(self.label_ortho, 1, 0, 1, 1)
        self.value_layout = QtWidgets.QGridLayout()
        self.value_layout.setHorizontalSpacing(6)
        self.value_layout.setObjectName("value_layout")
        self.gridLayout_2.addLayout(self.value_layout, 5, 0, 1, 3)
        self.label_ortho_val = QtWidgets.QLabel(DataWidget)
        self.label_ortho_val.setObjectName("label_ortho_val")
        self.gridLayout_2.addWidget(self.label_ortho_val, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        self.tableWidgetsum = MeasureTable(DataWidget)
        self.tableWidgetsum.setObjectName("tableWidgetsum")
        self.tableWidgetsum.setColumnCount(2)
        self.tableWidgetsum.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidgetsum.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableWidgetsum.setHorizontalHeaderItem(1, item)
        self.tableWidgetsum.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tableWidgetsum, 2, 0, 1, 3)
        self.pushButton_km = QtWidgets.QPushButton(DataWidget)
        self.pushButton_km.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_km.setText("")
        self.pushButton_km.setObjectName("pushButton_km")
        self.gridLayout_2.addWidget(self.pushButton_km, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(DataWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 4, 0, 1, 3)
        self.label_km = QtWidgets.QLabel(DataWidget)
        self.label_km.setObjectName("label_km")
        self.gridLayout_2.addWidget(self.label_km, 0, 0, 1, 1)
        self.pushButton_ortho = QtWidgets.QPushButton(DataWidget)
        self.pushButton_ortho.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_ortho.setText("")
        self.pushButton_ortho.setObjectName("pushButton_ortho")
        self.gridLayout_2.addWidget(self.pushButton_ortho, 1, 2, 1, 1)
        self.label_sum = QtWidgets.QLabel(DataWidget)
        self.label_sum.setObjectName("label_sum")
        self.gridLayout_2.addWidget(self.label_sum, 3, 0, 1, 1)
        self.label_sum_val = QtWidgets.QLabel(DataWidget)
        self.label_sum_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sum_val.setObjectName("label_sum_val")
        self.gridLayout_2.addWidget(self.label_sum_val, 3, 1, 1, 1)
        self.pushButton_sum = QtWidgets.QPushButton(DataWidget)
        self.pushButton_sum.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_sum.setText("")
        self.pushButton_sum.setObjectName("pushButton_sum")
        self.gridLayout_2.addWidget(self.pushButton_sum, 3, 2, 1, 1)

        self.retranslateUi(DataWidget)
        QtCore.QMetaObject.connectSlotsByName(DataWidget)

    def retranslateUi(self, DataWidget):
        _translate = QtCore.QCoreApplication.translate
        DataWidget.setWindowTitle(_translate("DataWidget", "Form"))
        self.label_km_val.setText(_translate("DataWidget", "Value Kilomater"))
        self.label_ortho.setText(_translate("DataWidget", "Orthogonal Distance [m]:"))
        self.label_ortho_val.setText(_translate("DataWidget", "Value Ortho"))
        item = self.tableWidgetsum.horizontalHeaderItem(0)
        item.setText(_translate("DataWidget", "Position [km]"))
        item = self.tableWidgetsum.horizontalHeaderItem(1)
        item.setText(_translate("DataWidget", "Distance [km]"))
        self.label_km.setText(_translate("DataWidget", "Position [km]:"))
        self.label_sum.setText(_translate("DataWidget", "Sum:"))
        self.label_sum_val.setText(_translate("DataWidget", "TextLabel"))
from ..db_streckenkm.measure_table import MeasureTable
